default:
  ERROR: 'datapackage.error'
  WARNING: 'datapackage.warning'
  TABULAR_FORMATS: ['csv', 'tsv', 'xls', 'xlsx']
  DEFAULT_DATA_PACKAGE_PROFILE: 'data-package'
  DEFAULT_RESOURCE_PROFILE: 'data-resource'
  DEFAULT_RESOURCE_ENCODING: 'utf-8'
  DEFAULT_FIELD_TYPE: 'string'
  DEFAULT_FIELD_FORMAT: 'default'
  DEFAULT_MISSING_VALUES: ['']
  DEFAULT_DIALECT:
    delimiter: ','
    doubleQuote: true
    lineTerminator: "\r\n"
    quoteChar: '"'
    skipInitialSpace: true
    header: true
    caseSensitiveHeader: false
